# Literature {#literature}

Understanding the equity benefit distribution of park access requires us to consider two integrated but rather distinct literatures. First, we consider the disparity in park utility perception among different populations. We subsequently consider quantitative techniques to evaluate the access that individuals have to park facilities.

## Sociodemographic variation in park utility

The idea that different racial, ethnic, or cultural groups have different recreational styles, and might thus have different needs and preferences for parks and open space, has been thoroughly discussed in the leisure studies literature. @husbands1995ethnicity offer a detailed review of that research as of the mid-1990s. In general, explanations for racial and ethnic differences in park use can be classified into two categories: cultural and lifestyle differences on the one hand, and discrimination and marginalization on the other.

@byrne2009nature summarize literature in the former category, noting that Black park users have been described as preferring more social, sports-oriented spaces, relative to white park users who prefer secluded natural settings [@washburne1978black; @hutchison1987ethnicity; @floyd1999convergence; @gobster2002managing; @payne2002examination; @ho2005gender]; Asian park users are described as valuing aesthetics over recreational spaces [@gobster2002managing; @payne2002examination; @ho2005gender]; and Latino park users are said to value group-oriented amenities like picnic tables and restrooms [@baas1993influence; @hutchison1987ethnicity; @irwin1990mexican]. @byrne2009nature criticize such scholarship as having grossly exaggerated ethno-racial differences in park use and preferences, and suggest a model for explaining park use based on four elements: Sociodemographic characteristics; park amenities and surrounding land uses; historical/cultural context of park provision (including development politics and discriminatory land-use policies); and individual perceptions of park space (including safety and sense of welcome).

@byrne2012green applies a cultural politics theoretical frame to why people of color are underrepresented among visitors to some urban parks. Focus groups of Latino residents of Los Angeles emphasized the importance of parks to children. Participants described visiting parks with their children and the positive and negatives associations that parks evoked of their own childhood memories of parks and wilderness. Participants described barriers to visiting parks including distance, inadequate or poorly maintained facilities, and fear of crime. They cited a lack of Spanish-language signage not only as a barrier to understanding but also as a signal that a park was not intended to serve Spanish speakers. Participants also expressed that they did not feel welcome in parks located in high-income or predominantly white neighborhoods because they expected that other park users would have racist attitudes, that a more boisterous Latino 'recreational style' would not be tolerated, or that there would be other behavioral norms they were not aware of.

In an observational and survey-based study of park users in Los Angeles,
@loukaitou1995urban found a high-level of enthusiasm for park use among Hispanic residents. While she found, consistent with prior research [@baas1993influence; @hutchison1987ethnicity; @irwin1990mexican], that Hispanic park users showed a preference for passive recreation, she found that to be the case for all other user groups as well. She also found that Hispanic park users were the most likely to actively appropriate and modify park space, for example, by bringing items from home. She found that Hispanic park users tended to visit parks as family groups; African American park users tended to visit parks as peer groups; Caucasian park users tended to visit parks alone; and Asian residents were least likely to visit parks, even in a predominantly Asian neighborhood. Interviews with local elderly Asian residents (Chinese immigrants) suggested that a lack of interest in American parks was rooted in perceptions of the ideal park as "an aesthetic element of gorgeous design," leaving them unimpressed with poorly landscaped American parks emphasizing recreational functions.

## Defining and measuring park accessibility

"Accessibility" is an abstract concept that describes how easily an individual can accomplish an activity at a particular space. Though not strictly quantifiable, the idea of quantifying this access is tempting and has been frequently attempted. @Handy1997 identify three broad types of accessibility measures: cumulative opportunity or isochrone measures, gravity-based measures, and utility-based measures. @Dong2006 follow the same basic classification approach as Handy and Neimeier, illustrating mathematically how the three different types of measures can be collapsed into each other. @GEURS2004127 group cumulative opportunity and gravity-based measures into a single category that they refer to as location-based measures. In this, @GEURS2004127 rely on the distinction that utility-based measures incorporate revealed preferences of individuals for particular destinations while location-based measures are entirely geo-spatial in their definition.

### Location-based measures of park accessibility

Cumulative opportunity measures are calculated by counting the number of origins or destinations within a threshold travel cost of a location (where cost might be some combination of distance, travel time, and/or monetary cost of travel). A strength of cumulative opportunity measures lies in their simplicity and intuitive interpretation. However, they may be too simple, especially with regard to trip costs near the threshold. An example of a cumulative opportunity measure might be the number of parks within a ten-minute walk of a person's home, or the number of households living within ten minutes of a park. This measure would imply that a household living immediately adjacent to a park has the same access to it as one that lives nine minutes away, but that a household living eleven minutes away has no access to it.

ParkScore [@parkscore2019], developed by the Trust for Public Land, is a popular measure of park accessibility that starts from a cumulative opportunity measure (the share of the population that resides within a 10-minute walk of a green space) and adjusts this value based on the total city green space, investment, and amenities weighted against the socioeconomic characteristics of the population outside of the 10-minute walk threshold. The resulting score is a convenient quantitative tool in estimating the relative quality of green space access across cities [@Rigolon2018]. ParkScore may be less useful at identifying the comparative quality of access within a city, particularly since the vast majorityof residents in dense areas like San Francisco (100\%) and New York City (99%) may live within the binary 10-minute walk threshold. The Centers for Disease Control and Prevention (CDC) has developed an "Accessibility to Parks Indicator" along similar lines [@Ussery2016], calculating the share of the population living within a half-mile of a park for each county in the U.S.

Gravity-based accessibility measures take a similar approach to cumulative opportunity measures, but theoretically include all possible destinations and weight them according to the travel cost that they impose, based on an impedance function (often a negative exponential calibrated to observed trip distributions). Cumulative opportunity measures may be considered a special case of gravity-based measures, where the impedance function takes the form of a binary step function that equals zero after a cutoff travel cost (which is why @GEURS2004127 classify them both as location-based). 

A major advantage of gravity-based accessibility measures lies in their consistency with travel behavior theory: Gravity-based measures have their roots in the trip distribution step of the traditional four-step travel demand forecasting method, where trips originating in a particular zone are distributed among destination zones, proportionate to each zone's gravity-based accessibility. Urban scholars have used gravity-based measures to explore the spatial distribution of park access across Tainan City, Taiwan [@chang2011exploring] and to estimate the relationship between park access and housing prices in Shenzhen, China [@wu2017spatial].

Some scholars have used location-based measures of park accessibility to evaluate equity in park access. @chang2011exploring use a gravity-based measure to determine that low-income neighborhoods have less access to parks than higher-income neighborhoods in Tainan City, Taiwan. @bruton2014disparities conduct a neighborhood-level analysis of park amenities in Greensboro, North Carolina, and find that low-income neighborhoods tend to have parks with more picnic areas, more trash cans, and fewer wooded areas, but they do not address the question of the extent to which different populations might value these different amenities. @kabisch2014green find that neighborhoods in Berlin with high immigrant populations and older populations likewise had less access to parks, and they pair these findings with survey results suggesting that these disparities are not consistent with the preferences expressed by those populations. 

### Utility-based measures of park accessibility

While traditional four-step travel demand models distribute zonal trips based on a gravity-based accessibility model, the travel demand modeling profession has shifted more recently towards a destination choice framework that distributes trips based on discrete-choice regression models. @mcfadden1974 applied discrete choice models to urban travel demand to predict mode choice, and modern disaggregate activity-based models apply them to all travel behavior choices, including to select among alternative routes or alternative destinations [@de2011modelling]. Though the application of random utility models to destination choice is not new [see @anas1983discrete], the increasing availability of computing resources makes estimating and applying discrete choice models on large alternative sets in a practical context more feasible.

Destination choice models estimate the probability of selecting a particular destination among a set of alternatives based on the relative attractiveness, or _utility_, of each alternative. Utility may be function of distance or travel time alone (in which case, a utility-based accessibility measure might be quite similar to a location-based measure), but the function can also incorporate other destination characteristics that lead one destination to be more highly-utilized than another. For a utility-based measure of park accessibility, these might include park size, cleanliness, or the availability of particular amenities. The degree to which these park and trip attributes influence the destination utility can be estimated statistically using survey data.

Though destination choice utility models have not commonly been used to measure park accessibility, scholars have acknowledged that park accessibility metrics should be linked with park use, since a park that has many visitors must by definition be accessible to those visitors. @McCormack2010 provide a comprehensive review of this literature; it is sufficient here to note that most studies find park use to depend on a complicated interplay between park size, maintenance, facilities, and travel distance. Many of these attributes are incorporated into ParkIndex [@Kaczynski2016], which estimates the resident park use potential within small grid cells by applying utility preference coefficients estimated from a survey in Kansas City.

There are limited examples of researchers using a destination choice model to predict recreation attractions. @Kinnell2006 apply a choice model to a survey of park visitors in New Jersey, and estimate the relative attractiveness of park attributes including playgrounds, picnic areas, and park acreage weighed against the travel disutility and the relative crime rate at the destination. In a similar study, @Meyerhoff2010 model the urban swimming location choice for a surveyed sample. In both studies, the researchers were attempting to ascertain which attributes of a recreation generated the most positive utility, and therefore which attributes should be prioritized for improvement. Though neither was attempting to understand relative park accessibility, @macfarlaneNYC applied the @Kinnell2006 estimates in an exploration of utility-based park accessibility and its relationship to aggregate health outcomes.

One primary obstacle to estimating discrete-choice models on the park destination problem has been the lack of sufficiently detailed, trip-level data on park users. Most destination choice models in practice are estimated from household travel surveys that must focus on all trip purposes, and necessarily group multiple recreation and social trips together [@nchrp716]. However, the advent of large-scale mobile device networks and the perpetual association of unique devices with unique users has given researchers a new opportunity to observe the movements and activity location patterns for large subsets of the population [@Naboulsi2016]. Such passively collected location data --- sometimes referred to part of a larger category of “Big Data” --- is a by-product of other systems including cellular call data records  [e.g., @Bolla2000; @Calabrese2011], probe GPS data [@Huang2015], and more recently Location Based Services (LBS) [@Roll2019; @Komanduri2017]. LBS use a network of mobile applications that obtain the users’ physical location at different points in the day. Commercial vendors repackage, clean, and scale these data to population or traffic targets and provide origin-destination flows to researchers and practitioners. @Monz2019, for example, demonstrate that passive device data can accurately estimate trip flows to natural recreation areas.

A number of methods have been proposed to develop destination choice  information from these passive data. @Bernardin2018 employs a passive origin-destination matrix as a shadow price reference in an activity-based location choice model, iteratively adjusting the calibration parameters of the choice utilities to minimize the observed error between the passive data and the modeled predictions. @tf_idea use the passive flow data as a probabilistic sampling frame to recreate individual trips through simulation. A similar method developed by @Zhu2018 uses the passive dataset directly, sampling 10,000 random trips from GPS traces of taxi trips in Shanghai and estimating a destination choice model. Employing the passive data set in this way provides the authors an opportunity to examine the choices of a large sample of a small population (taxi passengers). The @Zhu2018 methodology could be extended to other situations where collecting a statistically relevant survey sample would be prohibitively difficult, but where passive device location data reveals which destinations people choose among many observable options.

## Street Conversion Equity Analysis

In their analysis of over one thousand reallocations of street space that occurred in response to the global COVID-19 pandemic, @combs2021shifting find that a plurality created additional space for walking, cycling, and recreation, although some reallocated space to commerce (e.g. outdoor dining and shopping) or short-term parking to for urban freight or food delivery.

If we define an urban park as a public space that is designated for the purpose of recreation, exercise, and social gathering, then the rapid reallocation of street space to accommodate recreation and active travel could be characterized as a proliferation of small urban parks. Researchers at the Trust for Public Land have explicitly described the reallocation of street space from cars to pedestrians as a strategy to relieve pressure on parks [@hussain_parks_2020] and have suggested that these actions should (and, in New York, had failed to) prioritize areas that would otherwise have low access to parks [@compton_parks_2020]. @fischer_covid-19_2021 have likewise done an equity analysis of street reallocation from vehicles to pedestrians in three mid-sized Canadian cities and found that interventions were generally more common in places with higher proportions of white residents and fewer children. The analyses by both @compton_parks_2020 and @fischer_covid-19_2021 were both based on proximity alone rather than on utility-based accessibility measures.

Of course, streets that reallocate space for active travel and recreation do not have the amenities or general character of most parks, and classifying them as equivalent to their greener peers in an accessibility analysis would be erroneous for many reasons. But a utility-based accessibility framework would allow us to discount these street parks for the amenities they lack while also considering the benefits proffered by their availability and proximity. Further, we can model these tradeoffs with statistical weights determinable through observing park trip distribution patterns revealed through passive mobile device data.
