---
title: "If you build it who will come? Equity analysis of park system changes during COVID-19 using passive origin-destination data"
author:
  - name: Gregory S. Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: BYU
    footnote: 1
  - name: Carole Turley Voulgaris
    email: cvoulgaris@gsd.harvard.edu
    affiliation: Harvard
  - name: Teresa Tapia
    email: teresa.tapia@streetlightdata.com
    affiliation: StreetLight
address:
  - code: BYU
    address: Brigham Young University, Civil and Environmental Engineering Department, 430 Engineering Building, Provo, Utah 84602
  - code:  Harvard
    address: Harvard Graduate School of Design, 48 Quincy St, Cambridge, Massachussetts 02138
  - code: StreetLight
    address: StreetLight Data, Inc., San Francisco, California
footnote:
  - code: 1
    text: "Corresponding Author"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Journal of Transportation and Land Use"
bibliography: [book.bib]
layout: "3p, authoryear, review"
keywords:
  - Accessibility
  - Passive Data
  - Location Choice
  - Parks
abstract: |
 During the spring and summer of 2020, cities across the world responded to the global COVID-19 pandemic by converting roadway facilities into open pedestrian spaces. These conversions improved access to public open space, but measuring the variation in that improvement among different populations requires clear definitions of access and methods for measuring it. In this study, we evaluate the change in a utility-based park accessibility measure resulting from street conversions in Alameda County, California. Our utility-based accessibility measure is constructed from a park activity location choice model we estimate using mobile device data --- supplied by StreetLight Data, Inc. --- representing trips to parks in that county. The estimated model reveals heterogeneity in inferred affinity for park attributes among different sociodemographic groups. We find, for example, that neighborhoods with more lower-income residents and those with more residents of color show a greater preference for park proximty while neighborhods with higher incomes and those with more white residents show a greater preference for park size and amenities. We then apply this model to examine the accessibility benefits resulting from COVID-19 street conversionsto create a set of small park-like open spaces; we find that this has been a pro-social policy in that Black, Hispanic, and low-income households receive a disproportionate share of the policy benefits, relative to the population distribution. 
description: "Alameda Park Choice"
---

# Introduction {#intro}
Parks and other open spaces generate immense value for the public who are able
to access them. The @CityParksAlliance categorizes the observed benefits of
urban parks as encouraging active lifestyles [@Bancroft2015], contributing to
local economies, aiding in stormwater management and flood mitigation, improving
local air quality, increasing community engagement [@Madzia2018], and enhancing
public equity.

For many, the value of public parks and open public spaces increased during the
widespread lockdowns enacted in 2020 to slow the transmission of COVID-19. With
other entertainment venues shuttered and people otherwise confined to their
homes, periodic use of public space provided an opportunity for physical and
emotional relief unavailable in other forms. Paired with this increased demand
for public open space --- and the with the epidemiological requirement to leave
sufficient space between other users --- was the related collapse in demand for
vehicular travel. As a result, cities around the world began closing select
streets to automobile travel, thereby opening them as pedestrian plazas, open
streets, or slow streets [@glaser_can_2021; @schlossberg_rethinking_2021;
@combs2021shifting]. The effective result of this policy was to create a number
of "parks" in urban areas that may have had poor access previously.
Understanding the equitable distribution of these benefits is an important land
use policy issue. The potential for non-emergency temporary or permanent street
conversions also brings up interesting problems for land use and transportation
policy; indeed, the possibility for transportation infrastructure to *become* a
socially beneficial land use that goes beyond serving mobility needs is a
tantalizing proposition.

Unfortunately, quantifying the benefits derived from access to parks in general
is a complicated problem. Many previous attempts at quantifying access in terms
of isochronal distances or open space concentration have resulted in a
frustrating lack of clarity on the relationship between measured access and
measures of physical and emotional health [@Bancroft2015]. Central to this
confusion is the fact that people do not always use the nearest park, especially
if it does not have qualities that they find attractive. A better methodology
would be to evaluate the park activity location choices of people in a
metropolitan area to identify which features of parks --- distance, amenities,
size, etc. --- are valued and which are less valued. The resulting activity
location choice model would enable the evaluation of utility benefits via the
choice model logsum [@Handy1997; @DeJong2007].

In this study, we seek to evaluate the socio-spatial distribution of benefits
received by residents of Alameda County, California resulting from the
temporary conversion of streets to public open spaces during the spring and
summer of 2020. We estimate a park activity location choice model using
location-based services (LBS) data obtained through StreetLight Data, Inc., a
commercial data  aggregator. The resulting model illuminates the degree to which
simulated individuals living in U.S. Census block groups of varying
sociodemographic characteristics value the walking distance between their residence
and parks, the size of the parks, and the amenities of parks including sport
fields, playgrounds, and walking trails in Alameda county. We then apply this
model to examine the inferred monetary benefit resulting from the street
conversion policy, and its distribution among different sociodemographic groups.

The paper proceeds in the following manner: A [discussion](#literature) of prior
attempts to evaluate park accessibility and preferences is given directly. A
[Methodology](#methodology) section presents our data gathering and cleaning
efforts, the econometric framework for the location choice model, and the
approach taken to apply the models to analyze open streets projects. A
[Results](#results) section presents the estimated choice model coefficients
alongside a discussion of their implications, including the implied benefits
resulting from the street conversions in Alameda County. After presenting
[limitations](#limitations) and associated avenues for future research, a final
[Conclusions](#conclusions) section outlines the contributions of this study for
recreational trip modeling and location choice modeling more generally.
